version: 2.1
orbs:
  heroku: circleci/heroku@1.2

jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: Login to Heroku Container Registry
          command: |
            heroku container:login
      - run:
          name: Build and push Docker image
          command: |
            heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: Release the image
          command: |
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
  deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main