version: 2.1
orbs:
  heroku: circleci/heroku@1.2

jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: Set Heroku stack to container
          command: |
            heroku stack:set container -a $HEROKU_APP_NAME
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main